FROM ubuntu:22.10
MAINTAINER Mahesh <mahesh@nowhere.com>
RUN  apt-get update
RUN  apt install -y software-properties-common
RUN  add-apt-repository ppa:bkryza/clang-uml
RUN  apt-get update
RUN  apt install -y clang-uml

